### ISSUE TITLE
Getting this error: Kuna API request error: 503, message='Service Unavailable'

### ISSUE THREAD

**Issue by JuliusLedoux** [marthoc/kuna#13]
Running on Docker Container Home Assistant 0.95.4. Everything seems to work fine, but I am getting this error: Kuna API request error: 503, message='Service Unavailable'. It happens every time that motion occurs. The interesting thing is that after two hours I got the recordings on my folder (that's great). Maybe problems connecting with the Kuna service?
I only have one camera (the light type) and your custom component has been working well.

**Comment by marthoc** [comment]
I've done more testing and there doesn't seem to be any particular reason that this error is kicked out. This seems to happen specifically with the camera image update request, so possibly requesting too quickly the API errors back. It's probably harmless since the request is just going to try again at the next interval.
