### ISSUE TITLE
Integration Not Showing Up

### ISSUE THREAD

**Issue by dwvaughn** [marthoc/kuna#16]
I followed the simple instructions but for some reason the Integration does not show up when I try to add it.

**Comment by radiationnow** [comment]
Same issue for me; its loading, at least to the point where the log gives the "custom component" error, but not showing to add in the integrations page.

**Comment by jlax47** [comment]
@dwvaughn: Which simple instructions? They've changed over time, so if you followed an old guide that might be the problem.

@radiationnow: Can you copy out any relevant sections of the log file? 

My integration is still working, so it could be some new problem that's causing it, but I'd be happy to help troubleshoot the issues with you to the best of my ability.

**Comment by radiationnow** [comment]
The only thing showing in the log is the usual non-error: "You are using a custom integration for kuna which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant."

I had the custom component working previously with the non-integration version; wiped the directory and re-cloned, then restarted and I don't have the ability to add the integration.  (I've tried both with and without the kuna: line in my config.yaml.)

**Comment by radiationnow** [comment]
That's the problem: the Kuna integration isn't listed when I click the plus, so I can't add it.

**Comment by dwvaughn** [comment]
@jlax47 I was referring to the instructions in the GitHub readme.  I finally got it working but it never showed up under the "integrations" tab.  I think I was ultimately able to get it working by fixing my config file.  There was an error in the syntax that wasn't readily apparent.

**Comment by jlax47** [comment]
Ok. I just tested on a fresh install of hassio on a pi4. I followed the instructions and it didn't work on the first try. It turns out I needed two restarts of HA to make it work.

So I ran:
```
mkdir /config/custom_components
cd /config/custom_components
git clone https://github.com/marthoc/kuna
```

Then I restarted HA Twice and the integration will show up. If I had to guess, I think what happens is the dependencies are install on the first restart and become available after the second.

**Comment by marthoc** [comment]
@dwvaughn @radiationnow if you are seeing that message in the logs re custom component, OR aren’t seeing it under the integrations menu, then you aren’t using the latest version of the integration. If you were able to eventually set it up without going through configuration - integrations, then you aren’t using the latest version of the integration, because as of the newest version, you can ONLY set up through the integrations menu.

**Comment by radiationnow** [comment]
I just wiped out the directory again, re-cloned ("git clone https://github.com/marthoc/kuna"), and rebooted twice—still shows the "you are using a custom integration" message in the log, still doesn't show up in Integrations when I click the +.  No kuna: block in my config.yaml.  Running Hassio 100.3.  There's no py_cache directory created.

Is there some other bit of cruft from the pre-integration version that might be gumming things up?

**Comment by jlax47** [comment]
@radiationnow Do you have the ssh component for hassio installed? If you do, ssh into it and run:

```
cd /config/custom_components/kuna
git log -1
```

See if it has a commit date of:  `Mon Aug 26 21:21:21 2019`

**Comment by radiationnow** [comment]
It does.

**Comment by radiationnow** [comment]
Updated to 101.3 today and it works now, so who knows what was going on there.
